add deque
CUST-ACM/CUSTL pull request #6
Opened 2018-05-08 04:57 UTC by zhuyutian57

2018-05-08 05:15 UTC, wenpen requested changes
demo写太随便了。
逻辑大体看着ok没有细看，风格有些要修改的地方。

2018-05-08 05:15 UTC, wenpen commented on deque.h
> +-----------------------------------------------*/
注释与其他文件保持一致

2018-05-08 05:15 UTC, wenpen commented on deque.h
> +#include "allocator.h"
> 按字母顺序分别对每种类型的头文件进行二次排序是不错的主意。注意较老的代码可不符合这条规则，要在方便的时候改正它们。

Google C++ Style 1.5

2018-05-08 05:15 UTC, wenpen commented on deque_demo.cpp
> +	Q.clear();
蜜汁缩进？

2018-05-08 05:15 UTC, wenpen commented on deque_demo.cpp
> +    std::cout<<Q.size()<<'\n';
风格与其他语句保持一致

2018-05-08 05:15 UTC, wenpen commented on deque.h
> +
太多空行，其他文件也注意。

2018-05-08 06:24 UTC, wenpen approved these changes

2018-05-11 05:57 UTC, TanYz04 approved these changes

2018-05-11 07:25 UTC, merged