add list
CUST-ACM/CUSTL pull request #7
Opened 2018-05-08 07:46 UTC by TanYz04

2018-05-08 08:52 UTC, wenpen requested changes
demo太随便了，虽然现在是临时demo，之后替换，但是也要按照规范来

2018-05-08 08:52 UTC, wenpen commented on list.h
> +-----------------------------------------------*/
风格与其他文件保持一致

2018-05-08 08:52 UTC, wenpen commented on list.h
> +#include "allocator.h"
Google C++ Style 1.5

2018-05-08 08:52 UTC, wenpen commented on list.h
> +	_list_node<T>* _next;
缩进使用4空格替换tab

2018-05-08 08:52 UTC, wenpen commented on list.h
> +	typedef _list_iterator<T, T&, T*>	    _self;
右边对齐，参考其他文件

2018-05-08 08:53 UTC, wenpen commented on list.h
> +
像这里就不需要空行了，写的紧凑一点更利于阅读

2018-05-11 02:39 UTC, F-TD5X commented
travis ci 还没过呢……改改bug吧

2018-05-11 02:39 UTC, closed without merging