Rb_tree
CUST-ACM/CUSTL pull request #9
Opened 2018-05-12 06:19 UTC by F-TD5X

源码在 src，测试 demo 在 test
同时修改了 Makefile 和 Travis ci

Rb tree 代码很长，如果有空可以找找bug
demo 已加入部分基本操作的测试，已通过。

2018-05-12 06:26 UTC, F-TD5X commented
Travis Ci failed due to merge with master....

2018-05-12 06:39 UTC, F-TD5X commented
@wenpen merge后不能用你的 destory 了是怎么个操作法。。。

2018-05-12 07:01 UTC, wenpen requested changes
这一千多行拿头review= =壮哉，我觉得用起来稳出锅还难修啊。。。

出现了其他pr出现过的问题，建议过一遍看看。

PS：destroy拼不对我也很绝望啊？

2018-05-12 07:01 UTC, wenpen commented on Makefile
> +CFLAGS = -g -Wall -std=c++11
激进点吧，直接怼到14？

2018-05-12 07:03 UTC, wenpen commented on src/tree.h
> + **/
注释与其他文件保持一致

2018-05-12 07:04 UTC, wenpen commented on src/tree.h
> +#include "../allocator.h"
这相对路径失了智，先扔到一个目录下吧，之后研究下看看怎么改makefile依赖路径。

2018-05-12 07:04 UTC, wenpen commented on src/tree.h
> +#include "../allocator.h"
include规范，参考其他pr

2018-05-12 07:44 UTC, F-TD5X commented on Makefile
> +CFLAGS = -g -Wall -std=c++11
没用C++14 特性 就不怼上14了吧

2018-05-12 07:45 UTC, F-TD5X commented on src/tree.h
> +#include "../allocator.h"
还是建议把源代码 和测试代码分开放把。。。

2018-05-12 07:46 UTC, wenpen commented on Makefile
> +CFLAGS = -g -Wall -std=c++11
预留下吧，免得之后升级又回来修编译

2018-05-12 07:48 UTC, wenpen commented on src/tree.h
> +#include "../allocator.h"
这个也是为了以后考虑的，这样之后改好makefile依赖不需要再回头一个个改代码，而修改文件路径是非常简单的事情。

2018-05-12 07:59 UTC, F-TD5X commented on src/tree.h
> +#include "../allocator.h"
![default](https://user-images.githubusercontent.com/19651619/39955190-5d10b9aa-55fd-11e8-9bad-4e95cbfa3218.png)
比如这样的目录结构？

2018-05-12 08:02 UTC, wenpen commented on src/tree.h
> +#include "../allocator.h"
应该是一个目录存源代码，另外再开目录存单测和demo

2018-05-12 08:09 UTC, F-TD5X commented on src/tree.h
> +#include "../allocator.h"
那就两个目录分别存 demo 和 源码，然后makefile 编译参数加上 include ？

2018-05-12 08:15 UTC, wenpen commented on src/tree.h
> +#include "../allocator.h"
奥你说的对，我钻牛角尖了。就按你说的来搞吧

2018-05-12 08:22 UTC, F-TD5X commented on src/tree.h
> +#include "../allocator.h"
行

2018-05-12 08:44 UTC, wenpen commented
奥我忘了这个编译器版本特别低。。。。先不开14了
改完编译器版本再开14吧

2018-05-12 08:54 UTC, F-TD5X commented
GTMD travis ci

2018-05-12 10:46 UTC, wenpen approved these changes

2018-05-16 03:03 UTC, zhuyutian57 approved these changes

2018-05-16 03:04 UTC, merged